spring.application.name=discord-mcp
server.port=8080
server.forward-headers-strategy=framework

spring.ai.mcp.server.name=discord-mcp-server
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.protocol=STREAMABLE

logging.file.name=./target/logs/discord-mcp-server.log
